services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate --url tcp://mosquitto:1883
    depends_on:
      - mosquitto